[build]
  base = ""
  command = "pnpm run build:netlify"
  publish = "dist/client"
  # Alternative build command if main build fails:
  # command = "vite build --emptyOutDir && pnpm run build:server:simple"

[dev]
  command = "pnpm run dev"
  port = 5000
  targetPort = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.server]
  external_node_modules = ["express", "serverless-http", "express-session"]
